-- DATE & TIME FUNCTIONS
-- 1. GETDATE(), getDate(), current_timestamp, sysdatetime()
-- 2. datename(),
-- 3. datediff()
-- 4. dateadd()

SELECT GETDATE() AS TODAY_DATE;

SELECT SYSDATETIME() AS TODAY_DATE;

SELECT CURRENT_TIMESTAMP AS TODAY_DATE;


SELECT DATENAME(MONTH, CURRENT_TIMESTAMP) AS 'MONTH'; 

SELECT DATENAME(YEAR, CURRENT_TIMESTAMP) AS 'YEAR';

SELECT DATENAME(HOUR, CURRENT_TIMESTAMP) AS 'HOUR';

SELECT DATENAME(MINUTE, CURRENT_TIMESTAMP) AS 'MINUTES';


SELECT DATEDIFF(YEAR, 'JANUARY 6 1995', CURRENT_TIMESTAMP) AS "AgeInYears";

SELECT DATEDIFF(MONTH, 'JANUARY 6 1995', CURRENT_TIMESTAMP) AS "AgeInMonths";

SELECT DATEDIFF(YEAR, 'JANUARY 10 1997', 'December 31 2019') AS "AgeInYears";

select DATEADD(year,100,current_timestamp)as "100yearsFromNow";

select DATEADD(month,100,current_timestamp)as "100monthsFromNow";
